### ISSUE TITLE
Starting with macOS 12.2, AltTab only grabs windows in active spaces

### ISSUE THREAD

**Issue by skyzyx** [lwouis/alt-tab-macos#1324]
**Describe the bug**

* I work with 2 monitors
* I work almost exclusively in full-screen mode

I updated to macOS 12.2 Beta (21D5039d) this morning, and since then, AltTab only grabs the front-most full-screen app window from each of my displays — ignoring the full-screen windows that are not front-most.

I know that the full-screen support is buggy because this app has to use private APIs, etc., but I wanted to bring this situation to the attention of the developers as a known issue.

Usually when AltTab is missing windows, I can quit and re-launch the app to get it to pick up the current state of my environment. However, even this action no longer works as of this morning's macOS beta update.

**Screenshots / video**

http://s3.ryanparman.com.s3.amazonaws.com/alttab-bug-1.mp4

**Comment by dnivi3** [comment]
Seeing the same on macOS 12.2 (21D49), the production version of macOS 12.2.

**Comment by kaatt** [comment]
likely related to https://github.com/kasper/phoenix/issues/289 and https://github.com/ianyh/Amethyst/issues/1192

**Comment by dnivi3** [comment]
Looks like Amethyst has fixed this in https://github.com/ianyh/Amethyst/pull/1184

**Comment by lwouis** [comment]
@dnivi3 the code change you linked to is this:

![image](https://user-images.githubusercontent.com/106195/152257355-7f24877f-52f5-487a-90b7-b8a7ee716480.png)

Changing the order `remove -> add` to `add -> remove`. AltTab already does `add -> remove`:

![image](https://user-images.githubusercontent.com/106195/152257430-d32f87c2-80c2-461a-8f47-9caf40db6a93.png)

**Comment by dnivi3** [comment]
@lwouis yeah, I realised my layman non-technical understanding of this isn't helpful. Is there any I can help or contribute towards this getting fixed?

**Comment by lwouis** [comment]
@dnivi3 i'm afraid only code contributions would help. Please see https://github.com/lwouis/alt-tab-macos/issues/1179

**Comment by lwouis** [comment]
Related: #1351

**Comment by stevetodd** [comment]
Just to add the datapoint, the issue persists in the newly released macOS 12.3.

**Comment by radaczynski** [comment]
This behaviour is repeatable. I have 3 desktops. When restarting alt-tab, windows from the active one get detected correctly, the switcher works just as expected, while on the other desktops only the active window is shown in the switcher. Restarting the apps/reopening the windows causes them to be shown in the switcher.

**Comment by kaatt** [comment]
Allowing screen recording permissions to the app should fix this.

**Comment by radaczynski** [comment]
@kaatt  - were you refering to my comment? It does not fix this issue - AltTab had the permission to record screen all the time. Windows from the current desktop are detected just fine after restart of AltTab, but on other desktops only one window is detected (+ all the windows that are created after AltTab is launched).

**Comment by lwouis** [comment]
It seems that we could simply replace the call to `CGSAddWindowsToSpaces` with a call to `CGSMoveWindowsToManagedSpace`.

Can anyone confirm this would work?

**Comment by lwouis** [comment]
I experimented with replacing `CGSAddWindowsToSpaces` with `CGSMoveWindowsToManagedSpace`. It's not a 1-to-1 replacement. It doesn't move fullscreen windows. It successfully moves regular windows, and moves them back, but it doesn't do anything for fullscreen windows, thus AltTab doesn't see them.

**Comment by dnivi3** [comment]
@lwouis glad to hear it solves for regular windows, but shame with fullscreen ones. Selfishly, this solves for my use cases. Is there a branch I can build from to test this?

**Comment by lwouis** [comment]
> Is there a branch I can build from to test this?

i'm sorry, there isn't

**Comment by lwouis** [comment]
Interesting data point: https://github.com/lwouis/alt-tab-macos/issues/1088#issuecomment-1054595185

i wonder if HS works on macOS 12.3+. If it can still work it means they have a robust trick to deal with windows in other Spaces

**Comment by dnivi3** [comment]
> Interesting data point: [#1088 (comment)](https://github.com/lwouis/alt-tab-macos/issues/1088#issuecomment-1054595185)
> 
> i wonder if HS works on macOS 12.3+. If it can still work it means they have a robust trick to deal with windows in other Spaces

@lwouis I can confirm that HyperSwitch works just fine on macOS Monterey 12.4 (21F79) and is grabbing any and all windows, including in other spaces.

**Comment by lwouis** [comment]
Today I wanted to decompile the Skylight framework on 12.4. I went in my 12.4 VM, and got surprised that I couldn't find it at `/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight`:

![image](https://user-images.githubusercontent.com/106195/170813279-776ded5e-a45f-484c-bd02-35b73fdae6a6.png)

Furthermore, I thought "how can AltTab work if Skylight is missing?". I tried to run AltTab, and it seems to work fine.

But as I was testing AltTab, I noticed that the Spaces at the top of the screen, in Mission Control, look different from my main machine which is still on macOS 10.15:

10.15 | 12.4
-|-
![image](https://user-images.githubusercontent.com/106195/170813391-044ea8c8-8104-4622-849b-4ed8c7249897.png) | ![image](https://user-images.githubusercontent.com/106195/170813370-84a14362-01a9-4cc4-8edf-583860d225c7.png)

Anyone knows what's going on here? Why is Skylight not at the usual path, and did Apple change the UI for Mission Control?

**Comment by decodism** [comment]
@lwouis

> Why is Skylight not at the usual path

From the [Big Sur release notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes):

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache.

Hopper has a function to read from the DYLD shared cache.

> did Apple change the UI for Mission Control

Not to my knowledge. On your screenshot, it looks like the transparency was disabled.

**Comment by lwouis** [comment]
> Hopper has a function to read from the DYLD shared cache.

I googled that, and it's a pretty new feature in Hopper apparently. My version didn't support it for instance. I'm constantly amazed at how fast things get deprecated these days. Constant march forward :/

> On your screenshot, it looks like the transparency was disabled

But also, the Spaces "thumbnails" at the top are squarish now instead of rectangles. And they don't show the windows in each Space. Is that just on that VM, or it's like this now?

**Comment by decodism** [comment]
> My version didn't support it for instance

It seems that there are third party tools to extract from the cache.

> the Spaces "thumbnails" at the top are squarish now instead of rectangles

It looks like they are the same aspect ratio as your screenshot.

> they don't show the windows in each Space

It's your VM.

**Comment by lwouis** [comment]
@decodism you seem to be knowledgeable with decompiling. Could you please help me? I would like to investigate what happened to `CGSAddWindowsToSpaces` on macOS 12.2+, and why it stopped working.

### macOS 10.15

On macOS 10.15, I see this proc, and it seems to lead to a mach message, to `WindowServer` I imagine? So there is not much implementation, it's just messaging. Maybe I'm not reading it correctly though?

![image](https://user-images.githubusercontent.com/106195/170862395-6521e42b-91e2-4f92-8198-3e1998a4a083.png)
![image](https://user-images.githubusercontent.com/106195/170862424-4d635841-01c9-4f00-a768-dc59d62a4133.png)
![image](https://user-images.githubusercontent.com/106195/170862406-87a70fb8-5135-43c8-bc05-fd6e6a13c045.png)

### macOS 12.4

On macOS 12.4, I used the new Hopper feature for `DYLD shared cache`. But that only shows me strings which match, not procs. I don't know how to dig further with these things.

![image](https://user-images.githubusercontent.com/106195/170862479-67dda483-893c-45fb-a2c9-efb4c2716e9d.png)
![image](https://user-images.githubusercontent.com/106195/170862525-80627e56-fd4c-41d1-9e4e-62598491f78d.png)
![image](https://user-images.githubusercontent.com/106195/170862532-addb92f8-ca63-4d78-8bd6-e93a03fa17a7.png)

I have [investigated a lot of alternative APIs](https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1133917888) to replace `CGSAddWindowsToSpaces`. Nothing seems to cut it and be a good replacement. I don't think any other big projects in the community which relied on it has found a successful replacement yet.

I was hoping maybe that if I could look into the internal of `CGSAddWindowsToSpaces`, I could bypass calling it, and instead maybe call a sub-function, or maybe even directly send raw mach messages to the WindowServer to emulate the old behavior. We [already use this approach to focus windows](https://github.com/lwouis/alt-tab-macos/blob/1ac0494f963b1e9ea27fcecc717972ec81c8025c/src/logic/Window.swift#L186).

Any help would be amazing here, and I'm quite out of my expertise zone, and I feel sad thinking that AltTab is broken for users of macOS 12.2+

**Comment by kaatt** [comment]
@lwouis CGS* functions are in SkyLight; they’ve been renamed from CGS* to SLS* (the CGS variants still work)

CGSConnectionRef contains a mach port; SLS functions communicate with some service (likely WindowServer) over the mach port, sending raw payloads. Payload kind is determined by DWORD at msg_hdr[0x14] (likely msgh_id).

WindowServer is itself implemented in SkyLight: WindowServer binary merely executes SLXServer entrypoint, which checks flags and re-spawns WindowServer as a daemon (in classic Unix style; no launchd involvement).

SLXServer seems to be a massive loop, it’s a switch statement with 383 cases.

Also, Objective-See has some RE work on WindowServer/SLS: https://objective-see.com/blog/blog_0x2C.html

**Comment by koekeishiya** [comment]
`SLS` functions are the user-facing API of the WindowServer; they are essentially helper functions. The actual implementation is also in the SkyLight framework, with an *`X` prefix, which is what the server executes upon receiving a mach_msg of said type.

<img width="335" alt="Screenshot 2022-05-29 at 15 56 51" src="https://user-images.githubusercontent.com/6175959/170872829-46b7676b-a7e9-4b66-a8f5-3075237bfb1a.png">
:

**Comment by kaatt** [comment]
What headers/call incantation did you try for the transaction functions? I can test out on 12.3+

**Comment by koekeishiya** [comment]
```
extern CFTypeRef SLSTransactionCreate(int cid);
extern CGError SLSTransactionCommit(CFTypeRef transaction, int unknown);
extern CGError SLSTransactionMoveWindowsToManagedSpace(CFTypeRef transaction, CFArrayRef window_list, uint64_t sid);
extern CGError SLSTransactionAddWindowToSpace(CFTypeRef transaction, uint32_t wid, uint64_t sid);
extern CGError SLSTransactionRemoveWindowFromSpace(CFTypeRef transaction, uint32_t wid, uint64_t sid);

```

**Comment by lwouis** [comment]
@kaatt I didn't get the path from the search matches in Hopper, to getting the list of methods here:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/106195/170874060-9c79189d-8cbb-4373-a0dd-916b0af247bd.png">

How did the search in Hopper reveal to you the existence of `SLSTransactionAddWindowToSpace` for instance?

@koekeishiya 

On macOS 10.15, in the `__XAddWindowsToSpaces` function you mentioned, it seems to call a function called `_PKGSpacesAddWindowsWithConnection` internally to do the work:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/106195/170874119-fbb70f7e-ae6f-4f5e-b020-5dcf7ed4e76a.png">

This one has the `PKG` prefix instead of `CGS`/`SLS`. Have you investigated around that? Maybe that PKG function is still preserved on 12.2+ as it's more internal? Maybe there is generally interesting features within the PKG functions family?

And also, how do you investigate on macOS 12.2+? There is no `__XAddWindowsToSpaces` there, so it seems they make big changes to the SLS internals.

**Comment by kaatt** [comment]
> How did the search in Hopper reveal to you the existence of SLSTransactionAddWindowToSpace for instance?

I was probably searching for SLSTransaction. I also looked into `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/PrivateFrameworks/SkyLight.framework/SkyLight.tbd`

**Comment by lwouis** [comment]
> This one has the `PKG` prefix instead of `CGS`/`SLS`. Have you investigated around that? Maybe that PKG function is still preserved on 12.2+ as it's more internal? Maybe there is generally interesting features within the PKG functions family?

I found this string inside `SkyLight.framework`: `SkyLight/Server/Packages/PKGSpace.c`. So it seems they created packages inside SkyLight, and PKG may just be the way they are separating those packages. Here `PKGSpace` may be where they deal with Spaces.

Furthermore, inside the PKG call I mentioned above, they call `___WSWorkspacesAddWindowsWithConnection_block_invoke` which is probably `WS` = `WindowServer`

**Comment by Cnly** [comment]
I'm on macOS 12.4 (21F79) with alt-tab-macos 6.4.0. Prior to a few days ago everything worked fine and if not, relaunching the app would've fixed it. Then all of a sudden I ran into this problem and relaunching the app didn't fix things anymore. It seems to have started after I logged out and in again a few days ago. Today I tried rebooting and everything's working again.

**Comment by fieryorc** [comment]
AltTab is no longer showing windows correctly in spaces other than the one where alt-tab is started in. I have 3 spaces, and when i start alt tab, it shows the windows in current space correctly, but when I switch to another space, it either shows 1 window or no window. I have multiple windows open. Most of my windows are chrome and chrome apps. This is a blocker for me as I can use it anymore.

**Comment by kashanico** [comment]
Having a similar issue with dual monitors. Sometimes does not detect open windows and I have to restart AltTab to get it to recognize all open windows. Happens everytime I boot it up.

**Comment by lwouis** [comment]
@kashanico you're probably seeing https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1153229652 (last bullet point, and the general ticket), if it's not the issue in this thread here.

**Comment by probablykasper** [comment]
The way [Contexts](https://contexts.co/) works is that when you switch to a space, it'll scan all the windows in there. That would at least be a nice improvement, since right now it seems you have to open individual windows to get them scanned

**Comment by lwouis** [comment]
@probablykasper I've added logic like this for the next release. It will get all windows of a Space when you switch to that Space. It's not a full solution, but it's a nice mitigation of the issue.

**Comment by probablykasper** [comment]
That's great !!

**Comment by radaczynski** [comment]
well, from what I can tell, this has fixed the issue for me. Thanks a lot!

**Comment by dnivi3** [comment]
@lwouis I just wanted to thank you so much for adding this logic to AltTab! I can finally uninstall HyperSwitch and start using AltTab again!

**Comment by J-Siu** [comment]
I just notice this recently. And the strange part is, it is inconsistent between apps.

I have two steam games, "Undead Hord 2" and "Nova Drift". I play both in full screen. When I cmd+tad out of the game, I can see both in the task list. However, from desktop, when I try to cmd-tab back to the game, "Nova Drift" shows, while "Undead Hord 2" won't.

**Comment by lwouis** [comment]
It seems that [1Piece](https://app1piece.com/) is able to do it! I hope we can find out how they do it

**Comment by lwouis** [comment]
They use the same private method we do: ![Image](https://github.com/user-attachments/assets/41d21fdf-caa9-43e6-9311-8cb9b621b727)

They also use [CGWindowListCreateImageFromArray](https://developer.apple.com/documentation/coregraphics/1455730-cgwindowlistcreateimagefromarray)

I'm struggling to find the place where they somehow grab the AXRef

**Comment by lwouis** [comment]
@decodism Oh! Could you please share more about this process?

**Comment by koekeishiya** [comment]
If you can just use the pid and windowid to construct the AXUIElementRef on your like in the above code, you do not need to brute-force the ids. You can get all window ids across all spaces, together with their associated pid from unrestricted private APIs.


```C
int g_connection = SLSMainConnectionID();
int cid = 0;

uint64_t *space_list = ..; 
int space_count = ..;

uint64_t set_tags = 0;
uint64_t clear_tags = 0;
uint32_t options = include_minimized ? 0x7 : 0x2;

CFArrayRef space_list_ref = cfarray_of_cfnumbers(space_list, sizeof(uint64_t), space_count, kCFNumberSInt64Type);
CFArrayRef window_list_ref = SLSCopyWindowsWithOptionsAndTags(g_connection, cid, space_list_ref, options, &set_tags, &clear_tags);

CFTypeRef query = SLSWindowQueryWindows(g_connection, window_list_ref, *count);
CFTypeRef iterator = SLSWindowQueryResultCopyWindows(query);

while (SLSWindowIteratorAdvance(iterator)) {
    pid_t pid = SLSWindowIteratorGetWindowPID(iterator);
    uint32_t wid = SLSWindowIteratorGetWindowID(iterator);

   // construct your own AXUIElement using this info..
}
```

**Comment by koekeishiya** [comment]
Aight I see, that makes sense yeah; which is why we need to translate the element to the actual window id.

**Comment by lwouis** [comment]
Thanks a lot @decodism and @koekeishiya!

I've played around with these AXUIElement IDs. They seem to be scoped per process. That is, a process start at 0, and the ID increments with each new element. For instance:
* TextEdit has 1 window
* I brute force this array [10] (10 is the ID of the AXUIElement of that window)
* I create a new window. Array is now [10, 11]
* I remove the window. Array is now [10]
* I create a new window. Array is now [10, 12]

When I looked at Finder, the windows were already at 175. I imagine that for long-running processes, the number can go quite high.

That being said, most people eventually restart their mac, or close their apps. So probably brute forcing the first 1K or 10K IDs may do the trick for most users.

Do you have any better idea on how to refine this approach?

Thank you 🙇

**Comment by lwouis** [comment]
To everyone following this thread:

Could you please try out [this local build](https://github.com/user-attachments/files/18648943/AltTab.app.zip)? It uses the new trick. On my machine, it fixes this ticket! Could you please let me know if it works for you, and if launch performance is ok?

Thank you!

**Comment by metya** [comment]
HI!
I've tried the  new build and it doesn't work for me. But my problem is slightly different. I described my problem here #2257
1piece is perfectly work with this little arc windows in Arc Browser, but alt-tab is still missing its. 
I think that the part of the same problem. Apparently it does not work with this trick.

**Comment by lwouis** [comment]
Hi,

I found some cases like launching Notes.app where it would miss windows with the new approach. I decided to combine the previous and new approaches.

Could you [please try out this local build](https://github.com/user-attachments/files/18664126/AltTab.app.zip) and let me know?

Thank you 🙇

**Comment by koekeishiya** [comment]
I implemented a version of this in yabai now. Thanks @decodism; I credited you for the solution.

I used a combination of the private API I mentioned above to check the window-ids that actually exists.
Then I use the regular MacOS API to get the windows that we can, using the "proper" method.

I then diff the lists to get a list of the window-ids that are missing, and I use the element-id brute-force approach to build the rest of the elements. 

Instead of checking the AXRole of the element, I just retrieve the ID of the element using the _AXUIElementGetWindow function, and make sure that the element-id matches one that I expect (from the previous diff).

When all the missing window-ids have been matched I break the brute-force loop and all windows are successfully resolved.
This approach lets selectively brute-force only applications that have windows on inactive spaces.

**Comment by lwouis** [comment]
Thank you for sharing these insights!

At the moment, I have implement a basic brute-force from 0 to 1000. It takes around 15-20ms on my M2 macbook pro. I think it's reasonably fast given that we do this brute-forcing in a background thread, in an async way. The user will see these windows appear in the switcher, as we discover them.

I'm interested in reducing the compute of course. I've profiled it, and it all goes into the AX calls we make to the OS. For instance to get the subrole, or to get the window ID.

Indeed, it would be nice to limit these AX calls. I think we can use `CGWindowListCopyWindowInfo` to get a list of all windows across all Spaces and situations. We can filter those by PID, and sort them. Now we have a min CGWindowID and a max CGWindowID.

I think we can then try to reduce this range by checking on both sides if we already known the windows. Once we have unknown windows on both sides, we can't reduce the range further.

An issue I have then is: how do we get the AXUIElement ID from AXUIElement? Do you know how to do this @decodism?

Thank you

**Comment by koekeishiya** [comment]
@lwouis The element_id is stored inside a CFData which is referenced by the AXUIElementRef.

```
pid_t = 0x0158ef, element_id = hex 0x2c, decimal 44, window_id = hex 0x30ec, decimal 12524
  0000  59 8d e0 f0 01 00 00 01 80 59 00 20 66 e0 01 00  Y........Y. f...
  0010  ef 58 01 00 00 00 00 00 6f 63 6f 63 00 00 00 00  .X......ococ....
  0020  90 9f 07 01 00 60 00 00 00 00 00 00 00 00 00 00  .....`..........
<CFData 0x600001079f90 [0x1f5f9c8c0]>{length = 8, capacity = 8, bytes = 0x2c00000000000000}
read element_id: 44
```

Code in C:
```C
static inline CFDataRef ax_window_eid(AXUIElementRef ref)
{
    return *(CFDataRef *)((void *) ref + 0x20);
}

CFDataRef e_data = ax_window_eid(element_ref);
CFShow(e_data);

printf("read element_id: %lld\n", *(uint64_t*)CFDataGetBytePtr(e_data));
```

**Comment by lwouis** [comment]
Thank you @koekeishiya! I'll try this!

**Comment by koekeishiya** [comment]
I made a filtering function based on various window properties that I discovered by sampling a ton of window data, and it has been in use in yabai for 1year. The core part has been in use for several years at this point, but the edit 1year ago fixed something with hidden windows I believe it was. The filtering is complex enough that I won't try to explain it here, but you can find the function I use to grab window-ids here: https://github.com/koekeishiya/yabai/blob/master/src/space.c#L17

**Comment by koekeishiya** [comment]
The brute force method doesn't actually work after a clean reboot. There appears to be some state that is missing. After interacting with windows, the brute force method does start to work. I don't know exactly what is going on and have not had time to go deeper into it. However, that means the code needs to assume that it will fail and be failsafe. I will change how I use it in yabai to combine it with the approach I used before, instead of replacing what i did before.

**Comment by lwouis** [comment]
Thank you for sharing this @koekeishiya! It's surprising. For this project, it should be okay since we either grab windows with the method, or we don't. We don't keep an exact count of which windows are known and which have an AXRef. We can get away with that for now, I think.

By the way, I noticed that you've changed the way you focus/make_key the windows in yabai:

<img width="2160" alt="Image" src="https://github.com/user-attachments/assets/04622d81-2949-45b9-938e-7d61dd2244c8" />

I've been using your your technique for years now. Recently, people have complained about focus issues with some apps (#4192). Is that what you fixed in yabai? I see many follow-up commits. Are you satisfied with the current implementation?

<img width="671" alt="Image" src="https://github.com/user-attachments/assets/24b9590c-4950-4249-a232-63964544dd84" />

If it's working well, I'll update it in AltTab. Hopefully, it will improve focus and fix #4192!

Thank you 🙇
