### ISSUE TITLE
Windows restored after a reboot don't show in AltTab

### ISSUE THREAD

**Issue by juicetin** [lwouis/alt-tab-macos#1467]
**Describe the bug**

Windows are missing from Alt+Tab list that are reopened after a reboot, and need to be minimised, then un-minimised, to make them reappear

**Screenshots / video**

Will add later if needed

**Steps to reproduce the bug**

1. Open any number of windows in any workspace you want
2. Reboot, with the option to enabled to re-open windows on reboot (I'm not sure where this is, I think it was a one off thing I enabled the first time I rebooted?)
3. After boot, try to alt+tab on any workspace with 1 or more windows - none will show up
4. To get them to show up again, they need to be minimised to taskbar, then un-minimised

**Comment by lwouis** [comment]
Should be fixed in v6.32.0

**Comment by juicetin** [comment]
Thanks for reopening @lwouis - I'm on v6.32.0 and looks like it's still reproducible at the moment

**Comment by gregersn** [comment]
I have a smiliar issue, might be related. 
If I start AltTab after I have opened windows, only the windows on the active desktop are found by AltTab. 
Minimizing and restoring missing windows make them reappear. 
Macos: 12.3.1
AltTab 6.37.1

**Comment by lwouis** [comment]
@gregersn please see #1324

**Comment by lwouis** [comment]
I've dug into this again today, and come to the conclusion that it falls under the umbrella of #447. Indeed, the issue here is the following:

* We rely on subscribing to an app's notifications to know when it creates a new window
* When an app launches, its initial windows tend to not send such notifications. It could be a macOS bug, or it could be that technically by the windows are created right before we have a chance to subscribe to the app's notifications
* Such initial windows can be on other Spaces than the current Space
 
This happens for instance when an app is opened, and some of its windows are restored. If they were fullscreen, they will be restored on other Spaces. Sometimes macOS will then automatically focus on another Space to show the newly open window, but there is an animation to get there which could mean we don't ask for windows during it, and we don't get the window.

More importantly, sometimes macOS will not focus such initial window. For example, if the restored app had multiple windows fullscreen. Then it may focus on of those Space, but not both.

Because we get no notification, and we don't travel to all relevant Spaces, we miss those windows. Let's thus focus the discussion in #447.
