### ISSUE TITLE
Sometimes my tab gets "stuck" and "unstoppable" looping through open apps can be stopped only with escape

### ISSUE THREAD

**Issue by viking1304** [lwouis/alt-tab-macos#3839]
**Describe the bug**

I am using cmd+tab as my shortcut, with preview. Everything worked absolutely fine, until the last update.

After I updated to the latest version, sometimes my tab gets "stuck" and "unstoppable" looping through open apps starts. Looks like i can stop it only if I press escape.

<strike>
I am not sure when this exactly happens, but I will pay attention, and add more information later. I am currently using my MacBook without external monitor or keyboard, and I do not notice this problem at this moment.

Those are things that I plan to test:
- macbook without external keyboard or monitor
- macbook with external keyboard but without external monitor
- macbook with external monitor but without external keyboard
- macbook with external monitor and keyboard

If you have any more ideas what I could test, let me know and I will.</strike>

This happens even without external keyboard or monitor and its most probably related to https://github.com/lwouis/alt-tab-macos/issues/3840 or even the same issue.

**Steps to reproduce the bug**

1. Set shortcut for switch to cmd+tab
2. Use that shortcut
3. Looping through app list cant be stopped unless you use escape

**Your environment**

* AltTab version: 7.3.0
* macOS version: 15.1
* Other relevant info: external MX Keys Mini keyboard with Logi Options+ version 1.84.641293, using external monitor (but happens even without any of them)

**Comment by lwouis** [comment]
Hi,

We had something similar in #3117. We thought it was fixed.

Could you please share a recording of your screen when it happens?

Also, are you sure there is only 1 instance of AltTab running? (e.g. only 1 icon in the top menubar? Multiple instance will create crazy flickering/issues.

Thank you 🙇

**Comment by viking1304** [comment]
> Could you please share a recording of your screen when it happens?

Im fully aware that you can't do anything unless you reproduce the issue, or at least see what is happening with your own eyes. Unfortunately, recording this might be tricky. I am still not fully aware when it happens, since it happened just a few times today. As far as I am aware I was not doing anything else than what I usually do (just switching the active window). Most of the time, everything worked without any issue, but sporadicly this happened. Bugs that happens only under specific conditions are the worst for debugging, especially if you can't figure out the actual steps the reproduce the issue.

The other issue is that each time this thing stopped after I pressed escape, so I suspect pressing any other key will do the same, and that includes triggering the screen recording. Next time I notice this, I will first record the video with my phone, and than I will try do to screen recording.

And the last issue is that I am using preview, and this is my work computer, so I can't send any video with work related data. It would be easiest to disable previews, but I am not sure if this will happen with previews off. If that issue you mentioned happened with and without previews, I will disable previews right now. Otherwise I will need to play with this laptop when I am not working, in order to be able to close apps with sensitive data.

I am trying to make it happen again since you posted this, but without luck. Everything works normal. 🤷🏻‍♂️

> Also, are you sure there is only 1 instance of AltTab running? (e.g. only 1 icon in the top menubar? Multiple instance will create crazy flickering/issues.

My icons like to hide themselves under the camera cutout, which really grind my gears, so I can never rely on that. Activity monitor shows only one process.

**Comment by vladunev-tomtom** [comment]
I'd like to confirm that I also have seen similar behavior - Alt-Tab stuck in open state after releasing the key combination. 
The other case, looping though all open apps, has been happening for a long time. I think it's related to
a) me using graphically demanding programs on a laptop without a graphic card ;) (macbook pro M1)
b) macos giving low process priority to Alt-Tab (this in mswindows terms, not sure how much sense this makes on a mac)

**Comment by danzou56** [comment]
This is something I've experienced as well but have held off on filing a bug report due to the poor reproducibility (and also the fact that it only seems to happen on my work machine which is harder to move files off of). I will remark that the machine I see the problem on is a 16" M3 Max machine, but it _felt_ like it happened more when I used to use an 16" Intel Core i9 based machine.  

I will also try to see if I there are any conditions that can potentially reproduce the issue or if external peripherals are causing the issue. My work machine also has Logi+ installed.

**Comment by viking1304** [comment]
For the whole day I didn't had any single glitch, but one just happened a few seconds ago. I was switching apps as usual an then it started looping through the list until it reached the end. Than it just stoped and I cant reproduce that again, even I haven't closed or opened any single app. 🤷🏻‍♂️ If I counted correctly I have 26 windows open at this moment, but CPU is on about 15%, and memory is around 60%. I am not doing any excessive task at this moment.

**Comment by leaderkent** [comment]
I think I have the same issue. My shortcut is control + tab. After upgrade the app, the first time I press the shortcut is normal. And after that, when I press the shortcut again, it show the app list as usual, but the focus automatic switches from first app to the end again and again. Maybe it is the same looping as the title said?

**Comment by lwouis** [comment]
@vladunev-tomtom @danzou56 @viking1304 @leaderkent are you all also on AltTab v7.3.0?

Thank you

**Comment by viking1304** [comment]
Yes, I am using 7.3.0.

I have never experienced this before 7.3.0. Everything worked smoothly until the last update.

**Comment by vladunev-tomtom** [comment]
I was experiancing this on 7.xx. 
Since yesterday I'm back on 6.73 and it has not happened. I havent restarted the machine, same programs are running.

**Comment by leaderkent** [comment]
> @vladunev-tomtom @danzou56 @viking1304 @leaderkent are you all also on AltTab v7.3.0?
> 
> Thank you

I have the issue on v7.3.0 and I'm back to v6.72.0 now.

**Comment by michaelomichael** [comment]
I've experienced the same issue. I first noticed it happening with v6.72.0. Reverting to an earlier version seemed to help, although I don't see any changes that would explain why. After a while it started happening again.
 
It's definitely linked to CPU usage for me - any time I have CPU-heavy processes running, there seems to be a delay between the keydown event (the one that causes AltTab popup to appear) and the corresponding keyup event - often several seconds. The result is that the popup appears, detects that the key is down, and starts moving the selection down through the list of windows automatically.

Perhaps it would be possible to wait for a keyup event before allowing the selection to start scrolling like this?

**Comment by basil-gray** [comment]
Been noticing this for months, including on 7.5.0 that I updated to today. Like michaelomichael mentioned, it also only happens for me when I'm heavily multitasking with a lot of apps running. I'm on an M1 8GB Macbook AIr.

**Comment by michaelomichael** [comment]
Thanks so much for getting this new version out so quickly. I've been using v7.6.0 all day and it's been behaving perfectly, even under heavy load, so I think this may have sorted it. 😄

**Comment by basil-gray** [comment]
Hasn't happened for the two days I've been on 7.6.0. Thanks for the awesome update.

**Comment by imkebe** [comment]
I can also confirm the 7.6.0 version seems to fix the issue.

**Comment by lwouis** [comment]
Hi,

Wonderful! I'll close this issue for now. If you see issues on the latest version, please let me know here. If the issue is a big different, please open a new one.

Thank you everyone for your help 🙇
