### ISSUE TITLE
ESC not working

### ISSUE THREAD

**Issue by Allanwby0516** [lwouis/alt-tab-macos#4748]
**Describe the bug**

After updating to macOS 26 Tahoe, I noticed that when using AltTab, I can no longer press ESC to cancel and hide. I hope this can be fixed.

**Your environment**

* AltTab version: 7.28.0
* macOS version: 26.0
* Other relevant info: using external keyboard, multiple monitors

**Comment by lwouis** [comment]
I can't reproduce the issue on my machine

Perhaps linked to this shortcut?

<img width="676" height="500" alt="Image" src="https://github.com/user-attachments/assets/e54495ad-9d78-40dc-8253-f9607f9e2802" />

Do you use Alt or Command for the AltTab shortcut? Can you try to use the other to see if Escape works then?

**Comment by Allanwby0516** [comment]
Thanks for getting back to me. I turned off that shortcut but it still didn’t work.
I later tried fn + esc and that did the trick.
It’s a bit of a hassle though, so I just use the `~ key instead of esc now.

**Comment by marcbinz** [comment]
Hi @lwouis,

I have the same issue regarding the Esc key after upgrading to macOS Tahoe.
So maybe there is an incompatibility in some regards.

I am happy to help figuring it out. If you have any idea on how to get behind this issue, please let me know.
In the meantime I will try to figure it out as well 👀

**Comment by lwouis** [comment]
It's most likely something in the OS intercepting the escape key, thus AltTab doesn't react to it

**Comment by smallmain** [comment]
This issue exists, but a solution has not been found yet.

**Comment by marcbinz** [comment]
Just for reference:

This seems to be a general issue with macOS 26 Tahoe. Even the OS default Command+Tab does not work with Escape.
Even after closing all applications and other system modificators, the issue persists.

There is a workaround however using Karabiner Elements as outlined [on Reddit](https://www.reddit.com/r/MacOSBeta/comments/1na57ez/command_tab_escape_issue_and_workaround/).

**Comment by fplgusmao** [comment]
Was happening to me too in Tahoe. But disabling the game overlay shortcut fixed it for me 🙌

**Comment by lwouis** [comment]
I was able to reproduce it consistently, and I have the [new Game Overlay shortcut](https://private-user-images.githubusercontent.com/106195/489953361-e54495ad-9d78-40dc-8253-f9607f9e2802.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk3NTU3MzcsIm5iZiI6MTc1OTc1NTQzNywicGF0aCI6Ii8xMDYxOTUvNDg5OTUzMzYxLWU1NDQ5NWFkLTlkNzgtNDBkYy04MjUzLWY5NjA3ZjllMjgwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwNlQxMjU3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjkwYWQ5MzczYjRlMTllMTg4ODg3ODBlZDMzODg4YTU2M2QzNjdlMjk4YmYyYjEzMzZkMmMzZjcyZjU3N2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FxwvhJbdfes7HG5Ps-cIMsXu5pb7gsO6-RCVUxjcjn0) off.

Steps to reproduce:
* Alt+tab > Escape works
* Launch Mail.app (new install, nothing is setup yet)
* Alt+tab > Escape doesn't work

<img width="1392" height="832" alt="Image" src="https://github.com/user-attachments/assets/4e9cf13b-f25b-46c5-b614-a5bdf63a2ee6" />

**Comment by lwouis** [comment]
Looking at the logs, it seems that AltTab is simply not receiving any keyboard event in that case. I think the OS is intercepting it for something else.

I was spamming alt+esc when i suddenly heard the VoiceOver voice. Out of nowhere. With no UI on screen.

After digging in the settings, I found there is an Accessibility shortcut for reading the selected text: alt+esc. I think it's disabled by default. It was disabled for me (i.e. the toggle was off). Yet it still happened.

<img width="835" height="981" alt="Image" src="https://github.com/user-attachments/assets/aefb77f9-9349-45ee-a288-be53c8da533d" />

Thus my conclusion is that macOS has a bug where alt+esc for reading selected text is not fully disabled sometimes. Somehow, in my case, opening Mail.app triggers the bug, and the OS intercepts keys. AltTab can't do anything about this. I'll close this ticket as unactionable, unfortunately.

Hopefully Apple fixes this issue soon

**Comment by lwouis** [comment]
Furthermore, the issue is present with the native app-switcher. This definitely closes the question of AltTab being the source of the issue

**Comment by tcy6** [comment]
@Allanwby0516 @lwouis  This issue appears to have been resolved in Tahoe 26.1.

**Comment by lwouis** [comment]
I still faced it myself on macOS 26.1, with the native app switcher and also with AltTab. Something from macOS is intercepting keys

**Comment by KentGrigo** [comment]
I'm on Tahoe 26.4.1 and it's no longer an issue with the native app switcher.
I assume that there'll be no more fixes from Apple on this one.

I found that I can avoid the issue by pressing `Command` + `Fn` + `Esc`.
A temporary fix could be to add `Fn` when in switcher mode. 
`Command` + `Fn` + `Tab` seems to work just fine.
