### ISSUE TITLE
After Effects is broken in Altab

### ISSUE THREAD

**Issue by joureskoh-cmd** [lwouis/alt-tab-macos#4913]
**Describe the bug**

After Effects on macOS doesn’t show preview in the Altab and always appears last in the window order, regardless of the rules I set.

**Screenshots / video**

https://youtu.be/kJGiCtWiULY

**Steps to reproduce the bug**

1. Open up After Effects.
2. Activate Altab shortcut key.
3. Doesn't show AE preview, window order always at last.

**Your environment**

* AltTab version: 7.30.0
* macOS version: Tahoe 26.0.1

**Comment by lwouis** [comment]
Please try out the latest release I just pushed. It may detect the window.

If it doesn't, then it's most likely an issue with After Effects windows not being standard macOS windows. Adobe is famous for its cross-platform suite. Please contact their customer support. If AltTab doesn't see their window, then no Accessibility app does.

Thank you

**Comment by joureskoh-cmd** [comment]
Hi @lwouis, thanks for the reply, unfortunately After Effects still doesn't show with the latest release. I did try to use another app switcher - HyperSwitch and it is able to show After Effects window normally. Though I still prefer to use Alttab. Hope this can be resolve one day.
